name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: release
  cancel-in-progress: false

jobs:
  release:
    runs-on:
      - ubuntu-latest

    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - uses: googleapis/release-please-action@v5
        with:
          type: simple
          token: ${{ secrets.GH_TOKEN }}